import json
import logging
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from app.agent.state import MeetingState

logger = logging.getLogger(__name__)


def _clean_json(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1]
        if text.endswith("```"):
            text = text.rsplit("```", 1)[0]
    return text.strip()


_PROMPT = """You are analyzing a meeting transcript that was auto-generated by speech-to-text.

The transcript may have errors — technical names garbled, words misheard. Use context to understand intent.

Extract every action item: tasks assigned, bugs mentioned, things people agreed to do.
Infer the correct meaning even if the wording seems off.

Respond ONLY with valid JSON, no markdown fences:
{{
  "action_items": [
    {{
      "description": "what needs to be done (use correct technical terms)",
      "assignee": "person name or Unassigned",
      "due_hint": "timeframe if mentioned or null"
    }}
  ]
}}

Transcript:
{transcript}"""


async def extract_action_items(state: MeetingState) -> dict:
    llm = ChatOpenAI(model="gpt-4o", temperature=0)
    response = await llm.ainvoke(
        [HumanMessage(content=_PROMPT.format(transcript=state["transcript"]))]
    )
    try:
        data = json.loads(_clean_json(response.content))
        return {"action_items": data.get("action_items", [])}
    except (json.JSONDecodeError, AttributeError) as e:
        logger.error(f"Failed to parse extractor response: {e}\nRaw: {response.content!r}")
        return {"action_items": []}
