import json
import logging
import uuid
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from app.agent.state import MeetingState

logger = logging.getLogger(__name__)


def _clean_json(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1]
        if text.endswith("```"):
            text = text.rsplit("```", 1)[0]
    return text.strip()


_PROMPT = """You are a senior engineering manager creating Jira tickets from meeting transcripts.

The transcript was auto-generated by speech-to-text and may contain errors:
- Technical names may be garbled (e.g. "11 labs" = ElevenLabs, "open ai" = OpenAI, "land graph" = LangGraph)
- Words may be misheard (e.g. "repair" might mean "replace" or "delete", "create and delete" not "create and repair")
- Use the surrounding context to infer the correct technical intent

Your job:
1. Understand what was MEANT, not what was literally said
2. Use correct technical terminology in tickets
3. Write clear, actionable tickets a developer would understand

For each action item create a ticket with:
- title: Clear and actionable, max 8 words, correct technical names
- description: 2-3 sentences. What needs to be done, why, and any context from the meeting
- ticket_type: "Bug" if something is broken, "Task" if something needs to be built or done
- priority: "High" if urgent/blocking, "Medium" if normal sprint work, "Low" if nice-to-have
- assignee: exact name if mentioned, otherwise "Unassigned"

Respond ONLY with valid JSON, no markdown fences:
{{
  "tickets": [
    {{
      "title": "...",
      "description": "...",
      "ticket_type": "Bug|Task",
      "priority": "High|Medium|Low",
      "assignee": "..."
    }}
  ]
}}

Action items to convert:
{action_items}"""


async def generate_tickets(state: MeetingState) -> dict:
    llm = ChatOpenAI(model="gpt-4o", temperature=0)
    response = await llm.ainvoke(
        [
            HumanMessage(
                content=_PROMPT.format(
                    action_items=json.dumps(state["action_items"], indent=2)
                )
            )
        ]
    )
    try:
        data = json.loads(_clean_json(response.content))
        tickets = []
        for t in data.get("tickets", []):
            ticket_type = t.get("ticket_type", "Task")
            if ticket_type not in ("Bug", "Task"):
                ticket_type = "Task"
            tickets.append(
                {
                    "id": uuid.uuid4().hex[:8],
                    "title": t.get("title", ""),
                    "description": t.get("description", ""),
                    "ticket_type": ticket_type,
                    "priority": t.get("priority", "Medium"),
                    "assignee": t.get("assignee", "Unassigned"),
                    "approved": None,
                }
            )
        return {"tickets": tickets}
    except (json.JSONDecodeError, AttributeError) as e:
        logger.error(f"Failed to parse ticket_gen response: {e}\nRaw: {response.content!r}")
        return {"tickets": []}
